# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
if !Case.first
	Case.create(name: 'Automobile/ Bicycle/ Motorcycle/ Vehicle Accidents', summary: "Legal claims that arise from vehicle accidents are typically governed by the law of negligence.  Any individual who negligently operates a motor vehicle may be required to pay damages to an injured victim.  A personal injury case involving a vehicle accident may become formalized through civil court proceedings or may be resolved through an informal settlement before a lawsuit is filed.", description: "<p>Legal claims that arise from vehicle accidents are typically governed by the law of negligence.  Any individual who negligently operates a motor vehicle may be required to pay damages to an injured victim.  A personal injury case involving a vehicle accident may become formalized through civil court proceedings or may be resolved through an informal settlement before a lawsuit is filed.  Vehicle accidents can include:
</p>

<p><ul>
	<li><b>Admiralty and maritime law</b></li>
	<li><b>ATV accidents</b></li>
    <li><b>Automobile accidents:</b> A car accident is a collision involving an automobile and anything that causes damage to the automobile, including other automobiles, telephone poles, buildings and trees. Sometimes a car accident may also refer to an automobile striking a human or animal. Car accidents — also called traffic collisions, auto accidents, road accidents, personal injury collisions, motor vehicle accidents and crashes — kill an estimated 1.2 million people worldwide each year, and injure about forty times this number.
</li>
    <li><b>Aviation accidents</b></li>
    <li><b>Bicycle accidents:</b> According to the Federal Highway Administration, over 67,000 cyclists in the U.S. are injured every year in accidents involving motor vehicles.  Many cyclists who are injured in bicycle accidents are unaware that they have a personal injury case and that they may be entitled to compensation for injuries, pain and suffering, medical bills and lost incomes.  A cyclist may be entitled to receive compensation for an injury sustained because of a pothole, poor road or defective sidewalk.  There are state mandated residential and commercial bicycle laws, which entitle cyclists to observe different traffic rules than cars, trucks and other motorized vehicles.  This may mean that the cyclist is not legally responsible for an accident. </li>
    <li><b>Boating accidents</b></li>
    <li><b>Commercial bus accidents</b></li>
    <li><b>Cruise ship accidents</b></li>
    <li><b>Intersection accidents</b></li>
    <li><b>Motorcycle accidents:</b> Motorcycle riders are often exposed to dangers not met by automobile drivers and other motorists on the road.  The lack on any substantial protective barriers, as well as the difficulty that other motorists may have in seeing or stopping for a motorcycle, leaves riders prone to serious personal injury in the event of an accident.</li>
    <li><b>Pedestrian accidents</b></li>
    <li><b>Rear end collisions</b></li>
    <li><b>Semi-tractor trailer accidents</b></li>
    <li><b>School bus accidents</b></li>
    <li><b>SUV rollover accidents:</b> Although SUV rollovers do not occur as often as other automobile accidents, when they do occur they have a higher chance of resulting in serious injury or death, and are considered to be the most fatal type of vehicle accident on national roadways.  According to the Federal Highway Administration, SUV rollover accidents account for more than side and rear fatal vehicles combined and SUV's are three times more likely than the average passenger car rollover.<br />
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Although SUV's were designed primarily for the purpose of off-roading, manufacturers have since discovered their immense popularity as family vehicles.  Manufacturers have begun removing roll bars in current models.  SUV seat structures are not designed to keep occupants in place during a rollover regardless if seatbelts are worn.  Vehicle roofs, windshields and side windows easily collapse, increasing the risk of occupant head, brain and spinal cord and back injuries.  While the body of an SUV remains the same as it would if used for off-roading, the removal of the roll bars, combined with the high center gravity due to multiple passengers, make rollover accidents and occupant ejection that much more fatal.</li>

    <li><b>Train accidents: </b>Train accidents can result in injuries such as sprains and fractures, catastrophic injury such as head trauma, brain damage, paralysis and loss of lives or property.  Train accidents can include derailments, collisions with passenger vehicles or other trains, grade crossing accidents or accidents due to mechanical failure.  It is the railroad company's responsibility to ensure that there are appropriate signals and gates at every railroad crossing for safety precautions.  If the railroad company fails to take such precautions, they are liable for any injury or death that ensues.  Victims of train accidents may be entitled to compensation for pain and suffering, medical expenses, property damage, lost wages and loss of earning capacity.</li>
    <li><b>Truck accidents</b></li>
    <li><b>Yacht accidents</b></li>
</ul></p>

<p>The surviving family members of a fatally injured accident victim may be able to bring wrongful death charges against the defendant.</p>")

Case.create(name: 'Slip & Fall/Premises Liability', summary: 'Slip and fall accidents can happen anywhere and can cause serious personal injury. Most slip and falls happen in commercial settings, such as grocery stores, drug stores, office buildings, construction sites, gas stations and malls, but they also happen on private property.', description: "<p>Slip and fall accidents can happen anywhere and can cause serious personal injury.  Most slip and falls happen in commercial settings, such as grocery stores, drug stores, office buildings, construction sites, gas stations and malls, but they also happen on private property.  Premises Liability accidents can include toxic exposure, animal attacks, swimming pool accidents and amusement park ride accidents.  In any event, there exist duties on the part of the property owners to maintain the property responsibly and avoid the existence of hazardous conditions.
</p>

<p>Dangerous or defective conditions may be large or small, temporary or permanent.  Therefore, investigation of the claim is essential to a successful case.  Temporary conditions such as water on the floor of a grocery store, or snow and ice on the stairs of a restaurant need to be investigated quickly.</p>")

	Case.create(name: 'Medical Malpractice', summary: 'Medical malpractice is the failure of a health care provider to follow the accepted standards of practice of his or her profession in the community where the service is rendered.  If a physician was careless, lacked proper skills or disregarded standardized rules resulting in injury to a patient, a jury may find the health care provider liable for negligence.  Hospitals can also be held liable for the negligence of their employees, including staff nurses and technicians.', description: "<p>Medical malpractice is the failure of a health care provider to follow the accepted standards of practice of his or her profession in the community where the service is rendered.  If a physician was careless, lacked proper skills or disregarded standardized rules resulting in injury to a patient, a jury may find the health care provider liable for negligence.  Hospitals can also be held liable for the negligence of their employees, including staff nurses and technicians.</p>

<p>
<b>Examples of Medical Malpractice:</b>
<ul>
	<li>Failing to diagnose a tumor while reading an x-ray</li>
    <li>Puncturing a nearby organ or tissue during surgery</li>
    <li>Failing to order necessary and appropriate medical tests</li>
    <li>Failing to diagnose a condition in time to treat it properly</li>
    <li>Failing to refer a case to a medical specialist</li>
    <li>Prescribing incorrect medication</li>
    <li>Brain injury</li>
    <li>Birth Injury</li>
    <li>Cerebral Palsy</li>
    <li>Incorrect diagnosis that results in a failure to treat a medical condition</li>
    <li>Failing to properly administer anesthesia</li>
    <li>Emergency room negligence</li>
    <li>Dental malpractice</li>
    <li>Cosmetic surgery malpractice</li>
</ul></p>

<p>
<ul>
	<li><b>Birth Injury:</b> Birth injury malpractice is the failure of an obstetrician to properly perform his or her duties; i.e. failure to administer blood tests to detect abnormalities that can result in death or serious injury to both the mother and fetus.  If you have been injured because of improper medical care you may have a claim against the obstetrician/gynecologist who treated you.  However, statutes of limitations bar the filing of claims after a certain period of time following the negligent act.</li>
    <li><b>Cerebral Palsy:</b> Cerebral palsy is permanent brain injuries that affect an infant in the womb, during birth, or in the months following birth and is one of the most common birth injuries in the United States.  Cerebral palsy patients are subject to limited motor skills, speech difficulties and learning disabilities.  When cerebral palsy occurs as the result of medical malpractice, the responsible party inflicting said injuries can be held legally responsible.  Examples of medical malpractice during delivery include leaving the baby in the birth canal too long resulting in oxygen deprivation, and/or failing to perform or delaying a necessary C-section.</li>
    <li><b>Anesthesia Negligence:</b> Medical malpractice injuries can occur when anesthesia is improperly given or not given in a timely manner to a patient during a surgical procedure. If the failure of the anesthesiologist is the cause of injury or death to a patient, damages may be recoverable under the laws of medical malpractice.</li>
</ul></p>")

	Case.create(name: 'Spinal Cord Injury', summary: "Spinal cord injury (SCI) occurs when the nerves within the spinal canal are damaged.  Most SCI's are caused by trauma to the vertebral column, affecting the spinal cord's ability to send and receive messages between the brain and the body's systems that control sensory, motor and autonomic function.  Motor vehicle accidents are the leading cause of SCI, followed by acts of violence, falls, sports injuries and diseases such as polio, spina bifida and Friedreich’s Ataxia.  The spinal cord does not have to be severed in order for a loss of functioning to occur. In fact, in most people with SCI, the spinal cord is intact, but the damage to it results in loss of functioning.", description: "<p>Spinal cord injury (SCI) occurs when the nerves within the spinal canal are damaged.  Most SCI's are caused by trauma to the vertebral column, affecting the spinal cord's ability to send and receive messages between the brain and the body's systems that control sensory, motor and autonomic function.  Motor vehicle accidents are the leading cause of SCI, followed by acts of violence, falls, sports injuries and diseases such as polio, spina bifida and Friedreich’s Ataxia.  The spinal cord does not have to be severed in order for a loss of functioning to occur. In fact, in most people with SCI, the spinal cord is intact, but the damage to it results in loss of functioning.
</p>")
	Case.create(name: 'Traumatic Brain Injury', summary: "Traumatic brain injury (TBI) is a medical phrase used to describe the damage to the brain suffered by sudden impact or physical force to the head.  Essentially, the human brain floats in a fluid substance called cerebrospinal fluid.  TBI can result when the force of momentum causes the brain to impact against the skull.  This type of injury, often the result of hitting your head on the windshield, pavement or object, is frequently referred to as a “closed head injury.”  Whiplash can also cause TBI.  These closed head injuries can result in lasting physical and mental problems.", description: "<p>Traumatic brain injury (TBI) is a medical phrase used to describe the damage to the brain suffered by sudden impact or physical force to the head.  Essentially, the human brain floats in a fluid substance called cerebrospinal fluid.  TBI can result when the force of momentum causes the brain to impact against the skull.  This type of injury, often the result of hitting your head on the windshield, pavement or object, is frequently referred to as a “closed head injury.”  Whiplash can also cause TBI.  These closed head injuries can result in lasting physical and mental problems.</p")
	Case.create(name: 'Burn Injuries', summary: "People who have suffered and survived the agony of second, third and even fourth degree burns describe the pain they experienced as among the most severe of all traumatic injuries.  Personal injuries involving severe burns commonly result from explosions, premises fires, defective products, motor vehicle collisions, electric shock, as well as accidental exposure to harmful chemicals and radiation.", description: "<p>People who have suffered and survived the agony of second, third and even fourth degree burns describe the pain they experienced as among the most severe of all traumatic injuries.  Personal injuries involving severe burns commonly result from explosions, premises fires, defective products, motor vehicle collisions, electric shock, as well as accidental exposure to harmful chemicals and radiation.</p>")
	Case.create(name: 'Construction/ On-the-Job Accidents', summary: "Construction labor makes up one of the three most dangerous occupations in the United States today; each year producing thousands of debilitating injuries and wrongful deaths.  Factors that contribute to construction accidents include workers lifting loads with worn and weathered cables, working on elevated platforms without fall protection or wearing defective safety harnesses and lanyards, and/or working in trenches with improper benching and using outdated tools and equipment.  Farming and manufacturing accidents, as well as the oil and gas industry accidents can also cause serious injury and toxic exposure.", description: "<p>Construction labor makes up one of the three most dangerous occupations in the United States today; each year producing thousands of debilitating injuries and wrongful deaths.  Factors that contribute to construction accidents include workers lifting loads with worn and weathered cables, working on elevated platforms without fall protection or wearing defective safety harnesses and lanyards, and/or working in trenches with improper benching and using outdated tools and equipment.  Farming and manufacturing accidents, as well as the oil and gas industry accidents can also cause serious injury and toxic exposure.
</p>

<p><ul>
<li><b>Toxic Exposure:</b> Due to the tremendous growth of corporate industry in the United States over the past fifty years, the number of dangerous, toxic substances in the environment has grown significantly.  Some toxic substances are shown to cause substantial injury to people, such as lead-based paint (linked to brain damage, especially in children), asbestos (linked to lung cancer and restrictive lung disease), dry cleaning and other solvents (linked to brain damage and major organ damage), pesticides such as dioxin and DDT (linked to birth injuries) and toxic landfill waste (linked to leukemia).</li>
</ul></p>
")
	Case.create(name:'Dog/Animal Bites', summary: "Every year, millions of Americans are bitten by animals.  Being attacked by a dog is an extremely stressful event. Many dog bite injuries leave scars and have lasting emotional effects.  In every state, a dog owner is liable for bites to people inflicted viciously by a dog that previously bit a person viciously, or that were inflicted pursuant to the command of the dog owner.", description: "<p>Every year, millions of Americans are bitten by animals.  Being attacked by a dog is an extremely stressful event. Many dog bite injuries leave scars and have lasting emotional effects.  In every state, a dog owner is liable for bites to people inflicted viciously by a dog that previously bit a person viciously, or that were inflicted pursuant to the command of the dog owner.
</p>

<p>In almost all states, a bite victim can recover compensation from a person whose negligence caused the attack and from a person who violated a leash law, a trespass law applicable to dogs or other dog safety laws.  The owner or keeper of a dog is strictly liable for his or her dog, even if it is the first time the dog has injured someone.  As long as the injured victim was not trespassing, teasing or tormenting the dog, the keeper or owner of the dog is liable for any injuries sustained.  Compensation for a dog bite can include payment for medical bills, pain & suffering, mental anxiety, fear and scarring.
</p>")
	Case.create(name: 'Insurance Claims', summary: "Insurance claims are a notice for reimbursement from an insurance company when the insured has suffered a loss that is covered under the insurance policy. Insurance companies cannot refuse to pay a customer's claim without 'reasonable justification.'  This means that an insurance company must engage in a reasonable investigation and pay legitimate claims in a timely manner.  If an insurance company fails to handle its customer's claim properly, it may be held accountable for resulting economic losses, including lost wages, interest on money the insured borrowed to cover expenses while insurance benefits were wrongfully withheld, and loss due to damaged credit.", description: "<p>Insurance claims are a notice for reimbursement from an insurance company when the insured has suffered a loss that is covered under the insurance policy. Insurance companies cannot refuse to pay a customer's claim without 'reasonable justification.'  This means that an insurance company must engage in a reasonable investigation and pay legitimate claims in a timely manner.  If an insurance company fails to handle its customer's claim properly, it may be held accountable for resulting economic losses, including lost wages, interest on money the insured borrowed to cover expenses while insurance benefits were wrongfully withheld, and loss due to damaged credit.</p>")
	Case.create(name: 'Nursing Home Abuse & Neglect', summary: "Americans are living longer than ever before.  The fastest growing segment in the United States is the elderly population.  As a result of this demographic shift, many elderly Americans have become residents of nursing homes during their final years.  As many of these nursing homes are under-funded and understaffed, a disturbing incidence of neglect and abuse is being reported.  Injuries sustained by nursing home residents due to neglect and abuse often involve the inappropriate use of physical restraints, joint contractors, overuse of sedatives, unnecessary use of urinary catheters, loss of mobility, pressure sores and lack of nutrition with weight loss.", description: "<p>Americans are living longer than ever before.  The fastest growing segment in the United States is the elderly population.  As a result of this demographic shift, many elderly Americans have become residents of nursing homes during their final years.  As many of these nursing homes are under-funded and understaffed, a disturbing incidence of neglect and abuse is being reported.  Injuries sustained by nursing home residents due to neglect and abuse often involve the inappropriate use of physical restraints, joint contractors, overuse of sedatives, unnecessary use of urinary catheters, loss of mobility, pressure sores and lack of nutrition with weight loss.</p>")
	Case.create(name: 'Defamation (Libel & Slander)', summary: "A form of personal injury that does no physical harm but can be extremely harmful to person's reputation or character is called defamation.  Defamation is false and unprivileged spoken words (slander) or written publication (libel) which exposes any living person to hatred, contempt, ridicule or, which causes a person to be shunned or avoided, or which has a tendency to injure him or her in his or her trade or occupation.", description: "<p>A form of personal injury that does no physical harm but can be extremely harmful to person's reputation or character is called defamation.  Defamation is false and unprivileged spoken words (slander) or written publication (libel) which exposes any living person to hatred, contempt, ridicule or, which causes a person to be shunned or avoided, or which has a tendency to injure him or her in his or her trade or occupation.</p>")
	Case.create(name: 'Defective Products', summary: "Products liability refers to a manufacturer or seller being held liable for placing a defective product into the hands of a consumer.  Products liability cases may include defective or poorly designed machinery, tools, motor vehicle defects, recreational products, pharmaceuticals and other defective products and equipment.  A person injured by a defective or dangerous product may be eligible to file a lawsuit for product liability.  Damages can be recovered under one of the following categories:  strict products liability; negligence or breach of warranty.", description: "<p>Products liability refers to a manufacturer or seller being held liable for placing a defective product into the hands of a consumer.  Products liability cases may include defective or poorly designed machinery, tools, motor vehicle defects, recreational products, pharmaceuticals and other defective products and equipment.  A person injured by a defective or dangerous product may be eligible to file a lawsuit for product liability.  Damages can be recovered under one of the following categories:  strict products liability; negligence or breach of warranty.</p>")
	Case.create(name: "Workers' Compensation", summary: "Workers' compensation is insurance that an employer is required by law to carry in case an employee is injured on the job or becomes ill, temporarily or permanently disabled, or fatally injured due to circumstances surrounding his or her job.  Although workers' compensation laws vary from state to state, covered medical care generally includes: medical, surgical and hospital services; dental services; crutches; hearing aids; chiropractic treatment; physical therapy; nursing care and prescribed medications.  Additional monetary compensation may be provided if an injured employee is temporarily unable to work for more than a certain number of calendar days set by state law, hospitalized as an in-patient, or becomes permanently disabled due to a job-related injury or illness.  The right to receive medical treatment at the employer's expense typically continues as long as treatment is reasonable and necessary to treat the injury.", description: "<p>Workers' compensation is insurance that an employer is required by law to carry in case an employee is injured on the job or becomes ill, temporarily or permanently disabled, or fatally injured due to circumstances surrounding his or her job.  Although workers' compensation laws vary from state to state, covered medical care generally includes: medical, surgical and hospital services; dental services; crutches; hearing aids; chiropractic treatment; physical therapy; nursing care and prescribed medications.  Additional monetary compensation may be provided if an injured employee is temporarily unable to work for more than a certain number of calendar days set by state law, hospitalized as an in-patient, or becomes permanently disabled due to a job-related injury or illness.  The right to receive medical treatment at the employer's expense typically continues as long as treatment is reasonable and necessary to treat the injury.</p>")
	Case.create(name: "Wrongful Death", summary: "A wrongful death occurs when a person is killed due to the negligence or misconduct of another individual, company or organization.  A legal action for wrongful death belongs to the decedent's immediate family members, usually a surviving spouse and children, and sometimes parents.  Under certain circumstances, unrelated minor children living with and supported by the decedent may also bring a claim for wrongful death.", description: "<p>A wrongful death occurs when a person is killed due to the negligence or misconduct of another individual, company or organization.  A legal action for wrongful death belongs to the decedent's immediate family members, usually a surviving spouse and children, and sometimes parents.  Under certain circumstances, unrelated minor children living with and supported by the decedent may also bring a claim for wrongful death.  In order to bring a successful wrongful death cause of action, the following elements must be present:
</p>

<p><ul>
	<li>The death of a human being caused by another's negligent or intentional conduct</li>
    <li>The survival of family members who are suffering the loss of financial support, love, care, comfort, supervision, guidance, household assistance and general society previously provided by the deceased.</li>
</ul></p>

<p>The general rule in wrongful death cases is that one is entitled to recover both economic and non-economic damages which are suffered as a result of the loss of a loved one.  Economic damages in a wrongful death case include an award for the financial contributions which the decedent would have made to his or her spouse, children and/or parents had he or she survived.  It also includes the recovery for funeral service expenses in memory of the decedent and for burial cost.  Non-economic damages include loss of love, society, companionship, comfort, affection, solace or moral support.</p>")
		

end